services:
  - type: web
    name: my-stopwatch
    runtime: node
    plan: free
    buildCommand: cd server && npm run install:all && npm run build:all
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: prod
    healthCheckPath: /api/health
